apiVersion: apps/v1
kind: Deployment
metadata:
  name: productservice
spec:
  selector:
    matchLabels:
      app: productservice
  template:
    metadata:
      labels:
        app: productservice
    spec:
      containers:
        - name: productservice
          image: hana31/productservice:0.0.1
          imagePullPolicy: Always
          ports:
            - containerPort: 9090
